import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/globule/Navbar";
import Footer from "@/components/globule/Footer";
import image from "@/public/img/4ww.jpg";
import { getServerSession } from "next-auth";
import StoreProvider from "@/utils/redux/storeProvider";
import { Toaster } from "sonner";
import SessionProviders from "@/utils/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex  flex-col  min-h-screen  relative  bg-image`}
        style={{ backgroundImage: `url(${image.src})` }}
      >
        <SessionProviders session={session}>
          <StoreProvider>
            <div className="">
              <Navbar />
              {children}
              {/* <Toaster /> */}
            </div>
            <Footer />
          </StoreProvider>
        </SessionProviders>
      </body>
    </html>
  );
}
